### ISSUE TITLE
Fedora 25 |  Install failed from repo..

### ISSUE THREAD

**Issue by x09** [UnitedRPMs/WIKI#103]
Hi,

if i want install (dnf install ....) some packages from UnitedRPMs 

`mirrorlist=https://raw.githubusercontent.com/UnitedRPMs/unitedrpms.github.io/master/mirrorlist_F25_x86_64.txt`

I get errors

> [MIRROR] _package_name_.rpm: Interrupted by header callback: Server reports Content-Length: 15406 but expected size is: 23126            
> [FAILED] _package_name_.rpm: No more mirrors to try - All mirrors were already tried without success 
> 

or 

> Cannot download _package_name_.rpm: All mirrors were tried

where _package_name_.rpm any RPM from UnitedRPMs repo

Why?

**Comment by kuboosoft** [comment]
I am not sure about it, but rpm, selinux and others critical packages was updated by Fedora...

`dnf clean all && dnf -y update`

**Comment by paulcarroty** [comment]
```
$ rpm -K https://sourceforge.net/projects/unitedrpms/files/25/x86_64/kodi-eventclients-devel-17.0-4.20170205gita10c504.fc25.x86_64.rpm/download
https://sourceforge.net/projects/unitedrpms/files/25/x86_64/kodi-eventclients-devel-17.0-4.20170205gita10c504.fc25.x86_64.rpm/download: rsa sha1 (md5) pgp md5 OK
```

Maybe a temporary connection problem.

**Comment by x09** [comment]
No. Permanent.
I download all locally via https://github.com/SpiritQuaddicted/sourceforge-file-download/blob/master/sourceforge-file-downloader.sh

**Comment by paulcarroty** [comment]
@x09 https://sourceforge.net/p/forge/site-support/14684/

**Comment by paulcarroty** [comment]
@x09 https://sourceforge.net/p/forge/site-support/14684/#963f

Please provide your IP(s) for the SF support.

**Comment by x09** [comment]
Read access required

**Comment by paulcarroty** [comment]
![screenshot from 2017-03-22 10-43-54](https://cloud.githubusercontent.com/assets/1550705/24189153/990e33be-0eec-11e7-9e36-eeecc4586fe2.png)

**Comment by x09** [comment]
212.76.186.19

**Comment by paulcarroty** [comment]
The SF support thread is now public.

**Comment by kuboosoft** [comment]
@x09 remember, you can make a repository in Yandex for russian people...

**Comment by x09** [comment]
same error - https://github.com/UnitedRPMs/packages/issues/68

**Comment by paulcarroty** [comment]
@kuboosoft @x09 I can only promise to do some tests with gitlab. No another real alternatives except something like a Cloudflare.

**Comment by x09** [comment]
I tried to contact with yandex.. but unsuccessfully. Still wait answer from yandex

**Comment by paulcarroty** [comment]
@kuboosoft the GL quota is 100 GB per repo. I wrote above about Yandex - not agree any deals with such fucked corporations.

**Comment by kuboosoft** [comment]
@paulcarroty a extra mirror free is good, also we can't confuse your search engine with your tool bar; is different... Google used the same tactics in your begin... Remember when SF was accused with similar issue... then? Also Yandex offers a official mirror for Arch Linux! Then why not?

**Comment by paulcarroty** [comment]
> Google used the same tactics in your begin

Not the same. Read again what they do.

> Also Yandex offers a official mirror for Arch Linux! 

Why I must pay attention for Arch? Extraordinary success? Solutions?

**Comment by kuboosoft** [comment]
@paulcarroty http://www.zdnet.com/article/google-toolbar-a-new-malware-threat/


> Why I must pay attention for Arch? Extraordinary success? Solutions?


Simple Arch Linux is in the ranking of popularity... Also  has a mirror of Ubuntu thanks Tigro; Do you know who is Tigro? if not is bad... Can you offer a mirror? Are you going to invest in a mirror? Crickets around ...

**Comment by paulcarroty** [comment]
@kuboosoft I can't see any real evidences from your URL. AV companies produce the billions  same "researches". But **I personally** lost a hours for cleanup of my girl's laptop from your pretty goodness Yandex shit:

* this shit makes Yandex as homepage don't acceptable for changes
* this shit makes Yandex as non-changed default search
* this shit use a browser for random clicks

And I definitely not the alone in this game: http://imgur.com/a/UsN69

I don't care about Ubuntu, Tigro, ArchLinux, or their popularity. URPMS not use Yandex and I said why.

**Comment by kuboosoft** [comment]
Remember a mirror is different to a stupid toolbar; who installs a stupid search toolbar in Firefox with Linux or windows? hahaha; I prefer change the dns  or use duckduckgo (my current search engine, who show results omited by google...., liks above...) If you provides a best solution, welcome... You forget events no?  remember who suggested SF? and who cried as girl  for use of SF? same way if Yandex give us a mirror, welcome; SF doesn't work in all world because SF is hosted in USA; and it apply the rules of USA. without SF, is the end of the project. Also Yandex is a official mirror of the project Fedora... then is a whim stupid yours. We had our repository and packages  signed, man! Why the panic?. 

![Fedora Mirror list](https://preview.ibb.co/hQoiQa/Screenshot_20170401_204444.png)

**Comment by paulcarroty** [comment]
https://en.wikipedia.org/wiki/Reputation

Discussion is closed. I'm working now with Gitlab.

> Also Yandex is a official mirror of the project Fedora

And M$ is an official member of Linux Foundation. You should kiss their asses too?

**Comment by kuboosoft** [comment]
My unique interest is more mirrors... Japanese, Chinese, etc... I don't have preference; the world only want divide all (Please do not be part of it.)... duckduckgo is a USA Web search engine... and it has various sponsors , includes yahoo and others... 

Pay a mirror, buddy; and avoids suck... suck it. All mirror is welcome, And it does not matter if the mirror comes off of Snowden, Barack, Buddha, the Pope, Australia, Pionyang, the princess Diana .... etc!

**Comment by paulcarroty** [comment]
> My unique interest is more mirrors... Japanese, Chinese, etc.

Your unique interests is just a dream without doings. Without commercialization it remain only dreams. Say 'no' for drugs and make the projects who can earn for life, not a life of needy.  I will not pay for the mirror, create cool website, earn resources, create the koji etc individually just because: **I'm not a [Charles de Batz de Castelmore, dit d'Artagnan](https://en.wikipedia.org/wiki/Charles_de_Batz_de_Castelmore_d%27Artagnan)** - we do it together or don't.

> All mirror is welcome, And it does not matter if the mirror comes off of Snowden, Barack, Buddha, the Pope, Australia, Pionyang, the princess Diana .... etc!

It's only for you. But 'my reputation' = 'reputation of my projects' costs more than you (believe it?) narco's dreams and will be clean.

**Comment by paulcarroty** [comment]
Closed by https://github.com/UnitedRPMs/unitedrpms.github.io/commit/5e3f669a2d0a45dd1797b9505ff29488e5e05362

**Comment by kuboosoft** [comment]
@x09 You can make a complete backup with the next line (you need register in [SF](https://sourceforge.net/)):

```
USER=you_user_in_sf
rsync -avP --backup "$USER@frs.sourceforge.net:/home/frs/project/unitedrpms/" $HOME/unitedrpms
```
We feel the comments out of place; Unfortunately some team members have broken [interpersonal relationships](https://github.com/UnitedRPMs/packages/wiki/Code-of-conduct). Not only in UnitedRPMs...
